In [2]:
import numpy as np
import pandas as pd

In [4]:
target = np.arange(9).reshape(3,3)
target

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
target[np.ix_([1,2], [True, False, True])]

array([[3, 5],
       [6, 8]])

In [45]:
target[np.ix_([True, False, True], [True, False, True])]

array([[0, 2],
       [6, 8]])

In [33]:
L1, L2, L3 = list('abc'), list('def'), list('hij')
list(zip(L1, L2))

[('a', 'd'), ('b', 'e'), ('c', 'f')]

In [38]:
list(zip(*list(zip(L1, L2))))

[('a', 'b', 'c'), ('d', 'e', 'f')]

In [15]:
dict(zip(L1, L2))

{'a': 'd', 'b': 'e', 'c': 'f'}

In [6]:
map(lambda x: x ** 2, [1, 2, 3, 4, 5])

In [24]:
%timeit sum([Z[i][j]*((B[i]-U[j])**2).sum() for i in range(m) for j in range(n)])

34.7 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
%timeit ((np.ones((m,n))*(B**2).sum(1).reshape([m,1]) + np.ones((m,n))*(U.T**2).sum(0) - 2*B@U.T)*Z).sum()

607 µs ± 1.63 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [33]:
np.diff(np.flatnonzero(np.diff(np.r_[0,np.diff(x)==1,0])).reshape(-1,2),axis=1).max()+1

7

In [38]:
np.flatnonzero(np.diff(np.r_[0,np.diff(x)==1,0]))#.reshape(-1,2)

array([ 0,  5,  6, 12], dtype=int64)

In [56]:
np.r_[1,np.diff(x)!=1,1]

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int32)

In [67]:
x = np.array([-2,-1,0,1,2, 3, 5,6,7,8,9, 10,11,12])
np.diff(np.nonzero(np.r_[1,np.diff(x)!=1,1])).max()

8

In [35]:
np.r_[0,np.diff(x)==1,0]

array([0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0], dtype=int32)

In [17]:
pd.read_table('../data/my_table_special_sep.txt', sep=' \|\|\|\| ')

col1               col2
0   TS  This is an apple.
1   GQ    My name is Bob.
2   WT         Well done!
3   PT    May I help you?

In [10]:
data = [[1, 'a'], [2, 'b'], [3, 'c']]
df = pd.DataFrame(data = data,
                  index = ['row_%d'%i for i in range(3)],
                  columns=['col0', 'col1'])
df

col0 col1
row_0     1    a
row_1     2    b
row_2     3    c

In [11]:
df = pd.DataFrame(data = {'col_0': [1,2,3], 'col_1':list('abc')},
                  index = ['row_%d'%i for i in range(3)])
df

col_0 col_1
row_0      1     a
row_1      2     b
row_2      3     c

In [8]:
df = pd.read_csv('../data/learn_pandas.csv')
df['School'].drop_duplicates()

0    Shanghai Jiao Tong University
1                Peking University
3                 Fudan University
5              Tsinghua University
Name: School, dtype: object

In [33]:
df.set_index(['Grade','Name']).sort_index(level=['Grade','Name'],ascending=[True,False]).head()

School  Gender  Height  Weight  \
Grade    Name                                                                   
Freshman Yanquan Wang                Fudan University  Female   163.5    55.0   
         Yanqiang Xu                 Fudan University  Female   152.4    38.0   
         Yanqiang Feng            Tsinghua University  Female   162.3    51.0   
         Yanpeng Lv     Shanghai Jiao Tong University    Male     NaN    65.0   
         Yanli Zhang              Tsinghua University  Female   165.1    52.0   

                       Transfer  Test_Number   Test_Date Time_Record  
Grade    Name                                                         
Freshman Yanquan Wang         N            1  2019/11/19     0:04:07  
         Yanqiang Xu          N            1   2019/12/8     0:05:03  
         Yanqiang Feng        N            1  2019/12/10     0:04:13  
         Yanpeng Lv           N            1  2019/11/17     0:04:13  
         Yanli Zhang          N            1   2019/9/13     0:05:05

In [45]:
pd.Series([4.25,2.25,1.75,4.75]).mean()

3.25

In [72]:
s = pd.Series([1,3,6,10,15])
s.pct_change()

0         NaN
1    2.000000
2    1.000000
3    0.666667
4    0.500000
dtype: float64

In [78]:
s

0     1
1     3
2     6
3    10
4    15
dtype: int64

In [83]:
s = pd.Series([1, 3, 6, 10])
s.expanding().mean()

0    1.000000
1    2.000000
2    3.333333
3    5.000000
dtype: float64